version: '3.3'
services:
    flowable-all-in-one-app:
        image: flowable/all-in-one
        depends_on:
            - flowable-db
        environment:
            - JAVA_OPTS=-Xms512M -Xmx2G -Djava.security.egd=file:/dev/./urandom -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005
            - SERVER_PORT=9977
            - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
            - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-db:5432/flowable
            - SPRING_DATASOURCE_USERNAME=flowable
            - SPRING_DATASOURCE_PASSWORD=flowable
            #- LOGGING_LEVEL_ROOT=ERROR
            #- LOGGING_LEVEL_ORG_FLOWABLE=DEBUG
            - FLOWABLE_IDM_LDAP_ENABLED=true
            - FLOWABLE_IDM_LDAP_SERVER=ldap://svrone-esxi-host-one-keycloak-svr1
            - FLOWABLE_IDM_LDAP_PORT=10389
            - FLOWABLE_IDM_LDAP_USER=cn=admin,dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_PASSWORD=secret
            - FLOWABLE_IDM_LDAP_BASE_DN=dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_USER_BASE_DN=ou=users,dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_GROUP_BASE_DN=ou=groups,dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_QUERY_USER_BY_ID=(&(objectClass=inetOrgPerson)(uid={0}))
            - FLOWABLE_IDM_LDAP_QUERY_USER_BY_FULL_NAME_LIKE=(&(objectClass=inetOrgPerson)(|({0}=*{1}*)({2}=*{3}*)))
            - FLOWABLE_IDM_LDAP_QUERY_ALL_USERS=(objectClass=inetOrgPerson)
            - FLOWABLE_IDM_LDAP_QUERY_GROUPS_FOR_USER=(&(objectClass=groupOfUniqueNames)(uniqueMember={0}))
            - FLOWABLE_IDM_LDAP_QUERY_ALL_GROUPS=(objectClass=groupOfUniqueNames)
            - FLOWABLE_IDM_LDAP_QUERY_GROUP_BY_ID=(&(objectClass=groupOfUniqueNames)(uniqueId={0}))
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_USER_ID=uid
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_FIRST_NAME=cn
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_LAST_NAME=sn
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_EMAIL=mail
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_GROUP_ID=cn
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_GROUP_NAME=cn
            - FLOWABLE_IDM_LDAP_CACHE_GROUP_SIZE=10000
            - FLOWABLE_IDM_LDAP_CACHE_GROUP_EXPIRATION=180000
            - FLOWABLE_IDM_APP_ADMIN_USER_ID=flowable
            - FLOWABLE_IDM_APP_ADMIN_PASSWORD=test
            - FLOWABLE_IDM_APP_ADMIN_FIRST_NAME=Flowable
            - FLOWABLE_IDM_APP_ADMIN_LAST_NAME=Administrator
            - FLOWABLE_IDM_APP_ADMIN_EMAIL=admin@flowable.org
            - FLOWABLE_COMMON_APP_IDM-URL=http://flowable-all-in-one-app:8080/flowable-idm
            - FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=http://192.168.99.101:8080/flowable-idm
            - FLOWABLE_COMMON_APP_IDM_ADMIN_USER=flowable
            - FLOWABLE_COMMON_APP_IDM_ADMIN_PASSWORD=test
        ports:
            - 8080:8080
            - 5005:5005
        entrypoint: ["/wait-for-something.sh", "flowable-db", "5432", "PostgreSQL", "/opt/tomcat/bin/catalina.sh", "run"]
    flowable-db:
        image: postgres:9.6-alpine
        container_name: flowable-postgres
        environment:
            - POSTGRES_PASSWORD=flowable
            - POSTGRES_USER=flowable
            - POSTGRES_DB=flowable
        ports:
            - 5433:5432
        volumes:
            - all-in-one_pgdata:/var/lib/postgresql/data
        command: postgres
volumes: 
    all-in-one_pgdata:
