version: '3.3'
services:
    flowable-modeler-app:
        image: flowable/flowable-modeler
        container_name: flowable-modeler
        depends_on:
            - flowable-db
            - flowable-idm-app
            - flowable-task-app
        environment:
            - SERVER_PORT=8888
            - FLOWABLE_MODELER_APP_DEPLOYMENT-API-URL=http://flowable-task-app:9999/flowable-task/app-api
            #
            - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
            - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-db:5432/flowable
            - SPRING_DATASOURCE_USERNAME=flowable
            - SPRING_DATASOURCE_PASSWORD=flowable
            #
            - FLOWABLE_IDM_LDAP_ENABLED=true
            - FLOWABLE_IDM_LDAP_SERVER=ldap://svrone-esxi-host-one-keycloak-svr1
            - FLOWABLE_IDM_LDAP_PORT=10389
            - FLOWABLE_IDM_LDAP_USER=cn=admin,dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_PASSWORD=secret
            - FLOWABLE_IDM_LDAP_BASE_DN=dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_USER_BASE_DN=ou=users,dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_GROUP_BASE_DN=ou=groups,dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_QUERY_USER_BY_ID=(&(objectClass=inetOrgPerson)(uid={0}))
            - FLOWABLE_IDM_LDAP_QUERY_USER_BY_FULL_NAME_LIKE=(&(objectClass=inetOrgPerson)(|({0}=*{1}*)({2}=*{3}*)))
            - FLOWABLE_IDM_LDAP_QUERY_ALL_USERS=(objectClass=inetOrgPerson)
            - FLOWABLE_IDM_LDAP_QUERY_GROUPS_FOR_USER=(&(objectClass=groupOfUniqueNames)(uniqueMember={0}))
            - FLOWABLE_IDM_LDAP_QUERY_ALL_GROUPS=(objectClass=groupOfUniqueNames)
            - FLOWABLE_IDM_LDAP_QUERY_GROUP_BY_ID=(&(objectClass=groupOfUniqueNames)(uniqueId={0}))
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_USER_ID=uid
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_FIRST_NAME=cn
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_LAST_NAME=sn
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_EMAIL=mail
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_GROUP_ID=cn
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_GROUP_NAME=cn
            - FLOWABLE_IDM_LDAP_CACHE_GROUP_SIZE=10000
            - FLOWABLE_IDM_LDAP_CACHE_GROUP_EXPIRATION=180000
            #
            - FLOWABLE_IDM_APP_ADMIN_USER_ID=admin
            - FLOWABLE_IDM_APP_ADMIN_PASSWORD=secret
            - FLOWABLE_IDM_APP_ADMIN_FIRST_NAME=Flowable
            - FLOWABLE_IDM_APP_ADMIN_LAST_NAME=Administrator
            - FLOWABLE_IDM_APP_ADMIN_EMAIL=admin@flowable.org
            - FLOWABLE_COMMON_APP_IDM-URL=http://flowable-idm-app:8080/flowable-idm
            - FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=http://192.168.99.101:8080/flowable-idm
            - FLOWABLE_COMMON_APP_IDM-ADMIN_USER=admin
            - FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD=secret
        ports:
            - 8888:8888
        entrypoint: ["./wait-for-something.sh", "flowable-db", "5432", "PostgreSQL", "java", "-jar", "app.war"]
    flowable-task-app:
        image: flowable/flowable-task
        container_name: flowable-task
        depends_on:
            - flowable-db
            - flowable-idm-app
        environment:
            - SERVER_PORT=9999
            #
            - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
            - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-db:5432/flowable
            - SPRING_DATASOURCE_USERNAME=flowable
            - SPRING_DATASOURCE_PASSWORD=flowable
            #
            - FLOWABLE_IDM_LDAP_ENABLED=true
            - FLOWABLE_IDM_LDAP_SERVER=ldap://svrone-esxi-host-one-keycloak-svr1
            - FLOWABLE_IDM_LDAP_PORT=10389
            - FLOWABLE_IDM_LDAP_USER=cn=admin,dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_PASSWORD=secret
            - FLOWABLE_IDM_LDAP_BASE_DN=dc=flowable,dc=org
            #- FLOWABLE_IDM_LDAP_USER_BASE_DN=ou=users,dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_GROUP_BASE_DN=ou=groups,dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_QUERY_USER_BY_ID=(&(objectClass=inetOrgPerson)(uid={0}))
            - FLOWABLE_IDM_LDAP_QUERY_USER_BY_FULL_NAME_LIKE=(&(objectClass=inetOrgPerson)(|({0}=*{1}*)({2}=*{3}*)))
            - FLOWABLE_IDM_LDAP_QUERY_ALL_USERS=(objectClass=inetOrgPerson)
            - FLOWABLE_IDM_LDAP_QUERY_GROUPS_FOR_USER=(&(objectClass=groupOfUniqueNames)(uniqueMember={0}))
            - FLOWABLE_IDM_LDAP_QUERY_ALL_GROUPS=(objectClass=groupOfUniqueNames)
            - FLOWABLE_IDM_LDAP_QUERY_GROUP_BY_ID=(&(objectClass=groupOfUniqueNames)(uniqueId={0}))
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_USER_ID=uid
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_FIRST_NAME=cn
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_LAST_NAME=sn
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_EMAIL=mail
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_GROUP_ID=cn
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_GROUP_NAME=cn
            - FLOWABLE_IDM_LDAP_CACHE_GROUP_SIZE=10000
            - FLOWABLE_IDM_LDAP_CACHE_GROUP_EXPIRATION=180000
            #
            - FLOWABLE_IDM_APP_ADMIN_USER_ID=admin
            - FLOWABLE_IDM_APP_ADMIN_PASSWORD=secret
            - FLOWABLE_IDM_APP_ADMIN_FIRST_NAME=Flowable
            - FLOWABLE_IDM_APP_ADMIN_LAST_NAME=Administrator
            - FLOWABLE_IDM_APP_ADMIN_EMAIL=admin@flowable.org
            - FLOWABLE_COMMON_APP_IDM-URL=http://flowable-idm-app:8080/flowable-idm
            - FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=http://192.168.99.101:8080/flowable-idm
            - FLOWABLE_COMMON_APP_IDM-ADMIN_USER=admin
            - FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD=secret
        ports:
            - 9999:9999
        entrypoint: ["./wait-for-something.sh", "flowable-db", "5432", "PostgreSQL", "java", "-jar", "app.war"]
    flowable-idm-app:
        image: flowable/flowable-idm
        container_name: flowable-idm
        depends_on:
            - flowable-db
        environment:
            - SERVER_PORT=8080
            #
            - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
            - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-db:5432/flowable
            - SPRING_DATASOURCE_USERNAME=flowable
            - SPRING_DATASOURCE_PASSWORD=flowable
            #
            - FLOWABLE_IDM_LDAP_ENABLED=true
            - FLOWABLE_IDM_LDAP_SERVER=ldap://svrone-esxi-host-one-keycloak-svr1
            - FLOWABLE_IDM_LDAP_PORT=10389
            - FLOWABLE_IDM_LDAP_USER=cn=admin,dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_PASSWORD=secret
            - FLOWABLE_IDM_LDAP_BASE_DN=dc=flowable,dc=org
            #- FLOWABLE_IDM_LDAP_USER_BASE_DN=ou=users,dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_GROUP_BASE_DN=ou=groups,dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_QUERY_USER_BY_ID=(&(objectClass=inetOrgPerson)(uid={0}))
            - FLOWABLE_IDM_LDAP_QUERY_USER_BY_FULL_NAME_LIKE=(&(objectClass=inetOrgPerson)(|({0}=*{1}*)({2}=*{3}*)))
            - FLOWABLE_IDM_LDAP_QUERY_ALL_USERS=(objectClass=inetOrgPerson)
            - FLOWABLE_IDM_LDAP_QUERY_GROUPS_FOR_USER=(&(objectClass=groupOfUniqueNames)(uniqueMember={0}))
            - FLOWABLE_IDM_LDAP_QUERY_ALL_GROUPS=(objectClass=groupOfUniqueNames)
            - FLOWABLE_IDM_LDAP_QUERY_GROUP_BY_ID=(&(objectClass=groupOfUniqueNames)(uniqueId={0}))
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_USER_ID=uid
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_FIRST_NAME=cn
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_LAST_NAME=sn
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_EMAIL=mail
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_GROUP_ID=cn
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_GROUP_NAME=cn
            - FLOWABLE_IDM_LDAP_CACHE_GROUP_SIZE=10000
            - FLOWABLE_IDM_LDAP_CACHE_GROUP_EXPIRATION=180000
            #
            - FLOWABLE_IDM_APP_ADMIN_USER_ID=admin
            - FLOWABLE_IDM_APP_ADMIN_PASSWORD=secret
            - FLOWABLE_IDM_APP_ADMIN_FIRST_NAME=Flowable
            - FLOWABLE_IDM_APP_ADMIN_LAST_NAME=Administrator
            - FLOWABLE_IDM_APP_ADMIN_EMAIL=admin@flowable.org
            - FLOWABLE_COMMON_APP_IDM-ADMIN_USER=admin
            - FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD=secret             
        ports:
            - 8080:8080
        entrypoint: ["./wait-for-something.sh", "flowable-db", "5432", "PostgreSQL", "java", "-jar", "app.war"]
    flowable-admin-app:
        image: flowable/flowable-admin
        container_name: flowable-admin
        depends_on:
            - flowable-db
            - flowable-idm-app
            - flowable-task-app
        environment:
            - SERVER_PORT=9988
            # 
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_SERVER-ADDRESS=http://flowable-task-app
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_PORT=9999
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_CONTEXT-ROOT=flowable-task
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_REST-ROOT=process-api
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_SERVER-ADDRESS=http://flowable-task-app
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_PORT=9999
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_CONTEXT-ROOT=flowable-task
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_REST-ROOT=cmmn-api
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_SERVER-ADDRESS=http://flowable-task-app
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_PORT=9999
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_CONTEXT-ROOT=flowable-task
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_REST-ROOT=dmn-api
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_SERVER-ADDRESS=http://flowable-task-app
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_PORT=9999
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_CONTEXT-ROOT=flowable-task
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_REST-ROOT=form-api
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_SERVER-ADDRESS=http://flowable-task-app
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_PORT=9999
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_CONTEXT-ROOT=flowable-task
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_REST-ROOT=content-api
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_SERVER-ADDRESS=http://flowable-task-app
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_PORT=9999
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_CONTEXT-ROOT=flowable-task
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_REST-ROOT=app-api
            #
            - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
            - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-db:5432/flowable
            - SPRING_DATASOURCE_USERNAME=flowable
            - SPRING_DATASOURCE_PASSWORD=flowable
            #
            - FLOWABLE_IDM_LDAP_ENABLED=true
            - FLOWABLE_IDM_LDAP_SERVER=ldap://svrone-esxi-host-one-keycloak-svr1
            - FLOWABLE_IDM_LDAP_PORT=10389
            - FLOWABLE_IDM_LDAP_USER=cn=admin,dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_PASSWORD=secret
            - FLOWABLE_IDM_LDAP_BASE_DN=dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_USER_BASE_DN=ou=users,dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_GROUP_BASE_DN=ou=groups,dc=flowable,dc=org
            - FLOWABLE_IDM_LDAP_QUERY_USER_BY_ID=(&(objectClass=inetOrgPerson)(uid={0}))
            - FLOWABLE_IDM_LDAP_QUERY_USER_BY_FULL_NAME_LIKE=(&(objectClass=inetOrgPerson)(|({0}=*{1}*)({2}=*{3}*)))
            - FLOWABLE_IDM_LDAP_QUERY_ALL_USERS=(objectClass=inetOrgPerson)
            - FLOWABLE_IDM_LDAP_QUERY_GROUPS_FOR_USER=(&(objectClass=groupOfUniqueNames)(uniqueMember={0}))
            - FLOWABLE_IDM_LDAP_QUERY_ALL_GROUPS=(objectClass=groupOfUniqueNames)
            - FLOWABLE_IDM_LDAP_QUERY_GROUP_BY_ID=(&(objectClass=groupOfUniqueNames)(uniqueId={0}))
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_USER_ID=uid
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_FIRST_NAME=cn
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_LAST_NAME=sn
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_EMAIL=mail
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_GROUP_ID=cn
            - FLOWABLE_IDM_LDAP_ATTRIBUTE_GROUP_NAME=cn
            - FLOWABLE_IDM_LDAP_CACHE_GROUP_SIZE=10000
            - FLOWABLE_IDM_LDAP_CACHE_GROUP_EXPIRATION=180000
            #
            - FLOWABLE_IDM_APP_ADMIN_USER_ID=admin
            - FLOWABLE_IDM_APP_ADMIN_PASSWORD=secret
            - FLOWABLE_IDM_APP_ADMIN_FIRST_NAME=Flowable
            - FLOWABLE_IDM_APP_ADMIN_LAST_NAME=Administrator
            - FLOWABLE_IDM_APP_ADMIN_EMAIL=admin@flowable.org
            - FLOWABLE_COMMON_APP_IDM-URL=http://flowable-idm-app:8080/flowable-idm
            - FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=http://192.168.99.101:8080/flowable-idm
            - FLOWABLE_COMMON_APP_IDM-ADMIN_USER=admin
            - FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD=secret            
        ports:
            - 9988:9988
        entrypoint: ["./wait-for-something.sh", "flowable-db", "5432", "PostgreSQL", "java", "-jar", "app.war"]
    flowable-db:
        image: postgres:9.6-alpine
        container_name: flowable-postgres
        environment:
            - POSTGRES_PASSWORD=flowable
            - POSTGRES_USER=flowable
            - POSTGRES_DB=flowable
        ports:
            - 5433:5432
        command: postgres
